"""
Static metadata for each hazard: how to name it, how to draw it, how fast it
arrives, and — importantly — where its numbers come from.

`data_sources` is not decoration. A warning system that cannot say where a claim
came from is asking for trust it has not earned, so every card Tayari renders
carries its provenance down to the reader.
"""

from app.models.hazards import HazardType, Onset


class HazardMeta:
    __slots__ = (
        "hazard", "label", "short_label", "icon", "color", "onset",
        "lead_time", "description", "data_sources", "forecastable",
    )

    def __init__(
        self,
        hazard: HazardType,
        label: str,
        short_label: str,
        icon: str,
        color: str,
        onset: Onset,
        lead_time: str,
        description: str,
        data_sources: list[str],
        forecastable: bool,
    ):
        self.hazard = hazard
        self.label = label
        self.short_label = short_label
        self.icon = icon
        self.color = color
        self.onset = onset
        self.lead_time = lead_time
        self.description = description
        self.data_sources = data_sources
        # False for hazards nobody can forecast (earthquakes). Their card is
        # about preparedness and recent activity, never about prediction — and
        # the UI needs to know the difference so it never implies otherwise.
        self.forecastable = forecastable


HAZARD_META: dict[HazardType, HazardMeta] = {
    HazardType.FLOOD: HazardMeta(
        hazard=HazardType.FLOOD,
        label="River flooding",
        short_label="Flood",
        icon="🌊",
        color="#2E6F8E",
        onset=Onset.DAYS,
        lead_time="1-7 days",
        description=(
            "Rivers rising past the level at which they leave their channel and "
            "enter homes, fields and roads."
        ),
        data_sources=[
            "Copernicus GloFAS v4 river discharge (via Open-Meteo Flood API)",
            "Open-Meteo upstream rainfall forecast",
        ],
        forecastable=True,
    ),
    HazardType.EARTHQUAKE: HazardMeta(
        hazard=HazardType.EARTHQUAKE,
        label="Earthquake",
        short_label="Quake",
        icon="🏚️",
        color="#8A5A2B",
        onset=Onset.INSTANT,
        lead_time="No forecast is possible",
        description=(
            "Ground shaking from fault rupture. Nobody can predict the next one; "
            "what can be known is how often this ground has shaken before and "
            "what is shaking near you right now."
        ),
        data_sources=["USGS Earthquake Hazards Program (FDSN event catalog)"],
        forecastable=False,
    ),
    HazardType.TSUNAMI: HazardMeta(
        hazard=HazardType.TSUNAMI,
        label="Tsunami",
        short_label="Tsunami",
        icon="🌀",
        color="#1F5F73",
        onset=Onset.MINUTES,
        lead_time="Minutes to hours after the quake",
        description=(
            "Ocean waves generated by a seafloor earthquake. Warning time is "
            "measured from the rupture, not from a forecast — which is why the "
            "response is rehearsed in advance, not decided on the day."
        ),
        data_sources=[
            "USGS FDSN event catalog (offshore rupture detection)",
            "Copernicus DEM coastal geometry (via Open-Meteo Elevation API)",
        ],
        forecastable=False,
    ),
    HazardType.VOLCANO: HazardMeta(
        hazard=HazardType.VOLCANO,
        label="Volcanic activity",
        short_label="Volcano",
        icon="🌋",
        color="#A2412A",
        onset=Onset.HOURS,
        lead_time="Hours to weeks, when a volcano is monitored",
        description=(
            "Eruption, ashfall, lava and lahars from a nearby volcano. Unrest "
            "usually builds over days or weeks, so an eruption in progress "
            "nearby is genuinely actionable information."
        ),
        data_sources=[
            "Smithsonian Global Volcanism Program — Volcanoes of the World",
            "Smithsonian / USGS Weekly Volcanic Activity Report",
        ],
        forecastable=True,
    ),
    HazardType.CYCLONE: HazardMeta(
        hazard=HazardType.CYCLONE,
        label="Cyclone & severe storm",
        short_label="Storm",
        icon="🌪️",
        color="#4C5B8C",
        onset=Onset.DAYS,
        lead_time="1-5 days",
        description=(
            "Destructive wind, torrential rain and — on the coast — storm surge, "
            "whether from a named tropical cyclone or a severe local storm."
        ),
        data_sources=["Open-Meteo forecast (wind, gusts, surface pressure, rainfall)"],
        forecastable=True,
    ),
    HazardType.EXTREME_HEAT: HazardMeta(
        hazard=HazardType.EXTREME_HEAT,
        label="Extreme heat",
        short_label="Heat",
        icon="🔥",
        color="#C2603A",
        onset=Onset.DAYS,
        lead_time="2-7 days",
        description=(
            "Temperatures far above what this place is used to. Heat kills more "
            "people than any other weather hazard and does it quietly, which is "
            "why the threshold here is local rather than absolute."
        ),
        data_sources=[
            "Open-Meteo forecast (temperature, apparent temperature)",
            "Open-Meteo historical reanalysis (local climatology, 5 years)",
        ],
        forecastable=True,
    ),
    HazardType.WILDFIRE: HazardMeta(
        hazard=HazardType.WILDFIRE,
        label="Wildfire weather",
        short_label="Wildfire",
        icon="🔥",
        color="#B4501F",
        onset=Onset.HOURS,
        lead_time="1-5 days of dangerous conditions",
        description=(
            "Weather that lets a fire start easily and spread fast: hot, dry, "
            "windy air over fuel that has not seen rain."
        ),
        data_sources=[
            "Open-Meteo forecast (temperature, humidity, wind, rainfall)",
            "Open-Meteo historical reanalysis (antecedent dryness)",
        ],
        forecastable=True,
    ),
    HazardType.DROUGHT: HazardMeta(
        hazard=HazardType.DROUGHT,
        label="Drought",
        short_label="Drought",
        icon="🏜️",
        color="#9A7B3F",
        onset=Onset.SEASONS,
        lead_time="Weeks to months",
        description=(
            "A rainfall deficit deep enough to threaten crops, livestock and "
            "drinking water. It arrives slowly, which means there is real time "
            "to act — if anyone notices early enough."
        ),
        data_sources=["Open-Meteo historical reanalysis (5-year rainfall percentile)"],
        forecastable=True,
    ),
    HazardType.LANDSLIDE: HazardMeta(
        hazard=HazardType.LANDSLIDE,
        label="Landslide",
        short_label="Landslide",
        icon="⛰️",
        color="#6B5B45",
        onset=Onset.HOURS,
        lead_time="Hours, during and just after heavy rain",
        description=(
            "Saturated ground failing on a slope. It needs two ingredients — "
            "steep terrain and enough rain — and both are measurable."
        ),
        data_sources=[
            "Copernicus DEM terrain relief (via Open-Meteo Elevation API)",
            "Open-Meteo rainfall (antecedent and forecast)",
        ],
        forecastable=True,
    ),
}


def meta(hazard: HazardType) -> HazardMeta:
    return HAZARD_META[hazard]


def catalog() -> list[dict]:
    """Serializable hazard catalog for the API and the client."""
    return [
        {
            "hazard": m.hazard.value,
            "label": m.label,
            "short_label": m.short_label,
            "icon": m.icon,
            "color": m.color,
            "onset": m.onset.value,
            "lead_time": m.lead_time,
            "description": m.description,
            "data_sources": m.data_sources,
            "forecastable": m.forecastable,
        }
        for m in HAZARD_META.values()
    ]
